### Logear usuario
POST http://localhost:3500/Users/login
Content-Type: application/json

{
  "email_user": "joseasantana05@gmail.com",
  "password_user": "JSa06..."
}

### Crear usuario
POST http://localhost:3500/Users/register
Content-Type: application/json

{
    "name_user": "Jose Santana",
    "email_user": "joseasantana05@gmail.com",
    "password_user": "JSa06...",
    "username": "SenkuJS"
}

### Cerrar sesion
POST http://localhost:3500/Users/logout
Content-Type: application/json

{
  "email_user": "joseasantana05@gmail.com",
  "password_user": "JSa06..."
}

### Obtener todas las tipografias
GET http://localhost:3500/Tipography

### Obtener tipografia por id
GET http://localhost:3500/Tipography/1

### Obtener una tipografia por su fuente principal
GET http://localhost:3500/Tipography/NameMain/Roboto

### Obtener una tipografia por su fuente secundaria
GET http://localhost:3500/Tipography/NameSeco/Serif

### Obtener una tipografia por su tamaño de fuente
GET http://localhost:3500/Tipography/TamFont/16

### Obtener una tipografia por su tamaño en los parrafos
GET http://localhost:3500/Tipography/TamParagraph/16

### Obtener una Tipografia por su tamaño de fuente en los titulos
GET http://localhost:3500/Tipography/TamTitle/24

### Obtener una tipografia pór su tamaño de fuente en los subtitulos
GET http://localhost:3500/Tipography/TamSubtitle/20

### Crear una tipografia
POST http://localhost:3500/Tipography/1
Content-Type: multipart/form-data; boundary=CustomBoundary

--CustomBoundary
Content-Disposition: form-data; name="tam_font"

16
--CustomBoundary
Content-Disposition: form-data; name="tam_paragraph"

16
--CustomBoundary
Content-Disposition: form-data; name="tam_title"

24
--CustomBoundary
Content-Disposition: form-data; name="tam_subtitle"

20
--CustomBoundary
Content-Disposition: form-data; name="is_selected"

true
--CustomBoundary
Content-Disposition: form-data; name="main_font"; filename="Roboto.ttf"
Content-Type: application/x-font-ttf

< D:\Descargas\Ceviche_One,Permanent_Marker\Ceviche_One\CevicheOne-Regular.ttf
--CustomBoundary
Content-Disposition: form-data; name="secondary_font"; filename="San-serif.ttf"
Content-Type: application/x-font-ttf

< D:\Descargas\Ceviche_One,Permanent_Marker\Permanent_Marker\PermanentMarker-Regular.ttf
--CustomBoundary--


### Crear una tipografia con su fuente principal
POST http://localhost:3500/Tipography/Main/1
Content-Type: multipart/form-data; boundary=CustomBoundary

--CustomBoundary
Content-Disposition: form-data; name="tam_font"

16
--CustomBoundary
Content-Disposition: form-data; name="tam_paragraph"

16
--CustomBoundary
Content-Disposition: form-data; name="tam_title"

24
--CustomBoundary
Content-Disposition: form-data; name="tam_subtitle"

20
--CustomBoundary
Content-Disposition: form-data; name="archive_font"; filename="Roboto.ttf"
Content-Type: application/x-font-ttf

< ../font/Roboto.ttf
--CustomBoundary--

### Crear una tipografia con su fuente secundaria
POST http://localhost:3500/Tipography/Secondary/1
Content-Type: multipart/form-data; boundary=CustomBoundary

--CustomBoundary
Content-Disposition: form-data; name="tam_font"

16
--CustomBoundary
Content-Disposition: form-data; name="tam_paragraph"

16
--CustomBoundary
Content-Disposition: form-data; name="tam_title"

24
--CustomBoundary
Content-Disposition: form-data; name="tam_subtitle"

20
--CustomBoundary
Content-Disposition: form-data; name="archive_font"; filename="Serif.ttf"
Content-Type: application/x-font-ttf

< ../font/Serif.ttf
--CustomBoundary--



### Borrar una tipografia
DELETE http://localhost:3500/Tipography/1

### Obtener todos los conjuntos de colores
GET http://localhost:3500/Colors

### Obtener un conjunto de colores por id
GET http://localhost:3500/Colors/3

### Obtener un conjunto de colores por su color primario
GET http://localhost:3500/Colors/Primary/f00

### Obtener un conjunto de colores por su color secundario
GET http://localhost:3500/Colors/Secondary/0f0
### Obtener un conjunto de colores por su color terciario
GET http://localhost:3500/Colors/Ternary/00f

### Obtener un conjunto de colores por su color cuaternario
GET http://localhost:3500/Colors/Cuaternary/ff0

### Obtener un conjunto de colores por su color neutral
GET http://localhost:3500/Colors/Neutral/000

### Crear un conjunto de colores
POST http://localhost:3500/Colors/1
Content-Type: application/json

{
  "primary_color": "DFEEFF",
  "secondary_color": "2563EB",
  "ternary_color": "F97316",
  "cuarternary_color": "FFFFFF",
  "neutral_color": "374151",
  "is_selected": true
}

### Actualizar color por id
PATCH http://localhost:3500/Colors/2
Content-Type: application/json

{
  "primary_color": "DFEEFF",
  "secondary_color": "2563EB",
  "ternary_color": "F97316",
  "cuarternary_color": "FFFFFF",
  "neutral_color": "374151",
  "is_selected": false
}



### Borrar un conjunto de colores
DELETE http://localhost:3500/Colors/3
